In [11]:
import pandas as pd
import requests
from bs4 import BeautifulSoup


url=['https://www.imdb.com/list/ls068082370/','https://www.imdb.com/list/ls068082370/?sort=list_order,asc&st_dt=&mode=detail&page=2','https://www.imdb.com/list/ls068082370/?sort=list_order,asc&st_dt=&mode=detail&page=3']

In [12]:
#send request

page=[]
soup=[]
text=[]
for i in url:
    page.append(requests.get(i))

for i in page:
    soup.append(BeautifulSoup(i.text,'html.parser'))

In [13]:
#read name
n=[]
name=[]

for i in soup:
    n.append(i.find_all(class_='lister-item-content'))
for i in n:
    for item in i:
        name.append(item.a.text)

#read Id


id=[]
Id=[]
for i in soup:
    id.append(i.find_all(class_='lister-item-index unbold text-primary'))
for i in id:
    for item in i:
        Id.append(item.text)        
        
#read year
year=[]
yr=[]
for i in soup:
    yr.append(i.find_all(class_='lister-item-year text-muted unbold'))
for i in yr:
    for item in i:
        year.append(item.text.replace('(','').replace(')',''))
        
#read genre

genre=[]
gn=[]
for i in soup:
    gn.append(i.find_all(class_='genre'))
for i in gn:
    for item in i:
        genre.append(item.text)
for i in range(250):
    genre[i]=genre[i][1:-12]
    
#read run_time

run_time=[]
rt=[]
for i in soup:
    rt.append(i.find_all(class_='runtime'))
for i in rt:
    for item in i:
        run_time.append(item.text)

        
#read rating

r=[]
rating=[]
rt=[]
for i in soup:
    rt.append(i.find_all(class_='ipl-rating-star__rating'))
for i in rt:
    for item in i:
        r.append(item.text)
c=0
for i in range(5750):
    if i==c:
        rating.append(r[i])
        c=c+23
        
#read description

description=[]
ds=[]
for i in soup:
    ds.append(i.find_all('p'))
for i in ds:
    ds1=[]
    for item in i:
        ds1.append(item.text)
    ds1=ds1[14:]
    c=0
    for i in range(len(ds1)):
        if i==c:
            description.append(ds1[i])
            c=c+4
for i in range(250):
    description[i]=description[i].replace('\n    ','')
    

#read directors and actors

el=[]
x=[]
director=[]
stars=[]
d=[]
s=[]
for i in soup:
    el.append(i.find_all('p', class_='text-muted text-small'))
c=0
for i in el:
    for item in i:
        if c%3==1:
            x.append(item.text)
        c=c+1
for i in range(250):
    x[i]=x[i].replace('\n','')
    d.append(x[i].split('|')[0])
    s.append(x[i].split('|')[1])
for i in range(250):
    d[i]=d[i].replace('Director:','')
    d[i]=d[i].replace('Directors:','')
    director.append(d[i])
    s[i]=s[i].replace('Star:','')
    s[i]=[i].replace('Stars:','')
    stars.append(a[i])
for i in range(250):
    director[i]=director[i].replace('    ','')
    stars[i]=stars[i].replace('     ','')
    
    
#read number of votes and gross income
import numpy as np
x=[]
el=[]
for i in soup:
    el.append(i.find_all('p'))
for i in el:
    x1=[]
    for item in i:
        x1.append(item.text)
    x1=x1[14:]
    c=2
    for i in range(len(x1)):
        if i==c:
            x.append(x1[i])
            c=c+4
for i in range(250):
    x[i]=x[i].replace('\n','')
    x[i]=x[i].replace('Votes:','')
    x[i]=x[i].replace('Gross:','')
votes=[]
gross=[]
for i in range(250):
    list1=x[i].split('| ')
    if len(list1)==1:
        votes.append(list1[0])
        gross.append(np.NaN)
    else:
        votes.append(list1[0])
        gross.append(list1[1])

AttributeError: 'list' object has no attribute 'replace'

In [ ]:
#creating dataframe

my_tuple=list(zip(Id,name,year,run_time,genre,rating,description,director,stars,votes,gross))



df=pd.DataFrame(my_tuple,columns=['Id','Name','Year_of_release','Run_time','Genre','Rating','Description','Director','Stars','Votes','Collection'])

df.to_csv('IMDB_top50.csv', index=False)

In [14]:
df

,Id,Name,Year_of_release,Run_time,Genre,Rating,Description,Director,Stars,Votes,Collection
0,1.,The Shawshank Redemption,1994,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,Frank Darabont,"Tim Robbins, Morgan Freeman, Bob Gunton, Willi...","2,159,383",$28.34M
1,2.,The Godfather,1972,175 min,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Francis Ford Coppola,"Marlon Brando, Al Pacino, James Caan, Diane Ke...","1,482,004",$134.97M
2,3.,The Dark Knight,2008,152 min,"Action, Crime, Drama",9,When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart, M...","2,134,211",$534.86M
3,4.,The Godfather: Part II,1974,202 min,"Crime, Drama",9,The early life and career of Vito Corleone in ...,Francis Ford Coppola,"Al Pacino, Robert De Niro, Robert Duvall, Dian...","1,031,937",$57.30M
4,5.,Pulp Fiction,1994,154 min,"Crime, Drama",8.9,"The lives of two mob hitmen, a boxer, a gangst...",Quentin Tarantino,"John Travolta, Uma Thurman, Samuel L. Jackson,...","1,694,896",$107.93M
5,6.,Schindler's List,1993,195 min,"Biography, Drama, History",8.9,"In German-occupied Poland during World War II,...",Steven Spielberg,"Liam Neeson, Ralph Fiennes, Ben Kingsley, Caro...","1,120,114",$96.90M
6,7.,The Lord of the Rings: The Return of the King,2003,201 min,"Adventure, Drama, Fantasy",8.9,Gandalf and Aragorn lead the World of Men agai...,Peter Jackson,"Elijah Wood, Viggo Mortensen, Ian McKellen, Or...","1,533,424",$377.85M
7,8.,12 Angry Men,1957,96 min,Drama,8.9,A jury holdout attempts to prevent a miscarria...,Sidney Lumet,"Henry Fonda, Lee J. Cobb, Martin Balsam, John ...","617,471",$4.36M
8,9.,"Il buono, il brutto, il cattivo",1966,161 min,Western,8.8,A bounty hunting scam joins two men in an unea...,Sergio Leone,"Clint Eastwood, Eli Wallach, Lee Van Cleef, Al...","640,840",$6.10M
9,10.,Forrest Gump,1994,142 min,"Drama, Romance",8.8,"The presidencies of Kennedy and Johnson, the e...",Robert Zemeckis,"Tom Hanks, Robin Wright, Gary Sinise, Sally Field","1,662,318",$330.25M
10,11.,Inception,2010,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","1,892,659",$292.58M
11,12.,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,"Adventure, Drama, Fantasy",8.8,A meek Hobbit from the Shire and eight compani...,Peter Jackson,"Elijah Wood, Ian McKellen, Orlando Bloom, Sean...","1,548,721",$315.54M
12,13.,Fight Club,1999,139 min,Drama,8.8,An insomniac office worker and a devil-may-car...,David Fincher,"Brad Pitt, Edward Norton, Meat Loaf, Zach Grenier","1,725,176",$37.03M
13,14.,Dangal,2016,161 min,"Action, Biography, Drama",8.4,Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...","131,655",$12.39M
14,15.,Star Wars: Episode V - The Empire Strikes Back,1980,124 min,"Action, Adventure, Fantasy",8.7,After the Rebels are brutally overpowered by t...,Irvin Kershner,"Mark Hamill, Harrison Ford, Carrie Fisher, Bil...","1,078,606",$290.48M
15,16.,Star Wars,1977,121 min,"Action, Adventure, Fantasy",8.6,Luke Skywalker joins forces with a Jedi Knight...,George Lucas,"Mark Hamill, Harrison Ford, Carrie Fisher, Ale...","1,147,125",$322.74M
16,17.,The Matrix,1999,136 min,"Action, Sci-Fi",8.7,A computer hacker learns from mysterious rebel...,"Lana Wachowski, Lilly Wachowski","Keanu Reeves, Laurence Fishburne, Carrie-Anne ...","1,554,067",$171.48M
17,18.,Goodfellas,1990,146 min,"Biography, Crime, Drama",8.7,The story of Henry Hill and his life in the mo...,Martin Scorsese,"Robert De Niro, Ray Liotta, Joe Pesci, Lorrain...","933,503",$46.84M
18,19.,One Flew Over the Cuckoo's Nest,1975,133 min,Drama,8.7,A criminal pleads insanity and is admitted to ...,Milos Forman,"Jack Nicholson, Louise Fletcher, Will Sampson,...","852,678",$112.00M
19,20.,Cidade de Deus,2002,130 min,"Crime, Drama",8.6,"In the slums of Rio, two kids' paths diverge a...","Fernando Meirelles, Kátia Lund","Alexandre Rodrigues, Leandro Firmino, Matheus ...","659,198",$7.56M
20,21.,The Lord of the Rings: The Two Towers,2002,179 min,"Adventure, Drama, Fantasy",8.7,While Frodo and Sam edge closer to Mordor with...,Peter Jackson,"Elijah Wood, Ian McKellen, Viggo Mortensen, Or...","1,387,033",$342.55M
21,22.,Shichinin no samurai,1954,207 min,"Action, Adventure, Drama",8.6,A poor village under attack by bandits recruit...,Akira Kurosawa,"Toshirô Mifune, Takashi Shimura, Keiko Tsushim...","292,197",$0.27M
22,23.,Interstellar,2014,169 min,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...","1,347,914",$188.02M
23,24.,Kimi no na wa.,2016,106 min,"Animation, Drama, Fantasy",8.4,Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...","148,296",$5.02M
24,25.,The Silence of the Lambs,1991,118 min,"Crime, Drama, Thriller",8.6,A young F.B.I. cadet must receive the help of ...,Jonathan Demme,"Jodie Foster, Anthony Hopkins, Lawrence A. Bon...","1,169,665",$130.74M
25,26.,Léon,1994,110 min,"Action, Crime, Drama",8.5,"Mathilda, a 12-year-old girl, is reluctantly t...",Luc Besson,"Jean Reno, Gary Oldman, Natalie Portman, Danny...","955,153",$19.50M
26,27.,Se7en,1995,127 min,"Crime, Drama, Mystery",8.6,"Two detectives, a rookie and a veteran, hunt a...",David Fincher,"Morgan Freeman, Brad Pitt, Kevin Spacey, Andre...","1,327,204",$100.13M
27,28.,Saving Private Ryan,1998,169 min,"Drama, War",8.6,"Following the Normandy Landings, a group of U....",Steven Spielberg,"Tom Hanks, Matt Damon, Tom Sizemore, Edward Burns","1,143,620",$216.54M
28,29.,The Usual Suspects,1995,106 min,"Crime, Mystery, Thriller",8.5,A sole survivor tells of the twisty events lea...,Bryan Singer,"Kevin Spacey, Gabriel Byrne, Chazz Palminteri,...","928,419",$23.34M
29,30.,Sen to Chihiro no kamikakushi,2001,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",Hayao Miyazaki,"Daveigh Chase, Suzanne Pleshette, Miyu Irino, ...","576,948",$10.06M
...,...,...,...,...,...,...,...,...,...,...,...
220,221.,The Wizard of Oz,1939,102 min,"Adventure, Family, Fantasy",8,Dorothy Gale is swept away from a farm in Kans...,"Victor Fleming, George Cukor, Mervyn LeRoy, No...","Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr","357,403",$2.08M
221,222.,Rush,I 2013,123 min,"Biography, Drama, Sport",8.1,The merciless 1970s rivalry between Formula On...,Ron Howard,"Daniel Brühl, Chris Hemsworth, Olivia Wilde, A...","402,386",$26.95M
222,223.,The Truman Show,1998,103 min,"Comedy, Drama, Sci-Fi",8.1,An insurance salesman discovers his whole life...,Peter Weir,"Jim Carrey, Ed Harris, Laura Linney, Noah Emme...","861,234",$125.62M
223,224.,Platoon,1986,120 min,"Drama, War",8.1,A young soldier in Vietnam faces a moral crisi...,Oliver Stone,"Charlie Sheen, Tom Berenger, Willem Dafoe, Kei...","358,749",$138.53M
224,225.,Million Dollar Baby,2004,132 min,"Drama, Sport",8.1,A determined woman works with a hardened boxin...,Clint Eastwood,"Hilary Swank, Clint Eastwood, Morgan Freeman, ...","597,749",$100.49M
225,226.,The Bourne Ultimatum,2007,115 min,"Action, Mystery, Thriller",8,Jason Bourne dodges a ruthless C.I.A. official...,Paul Greengrass,"Matt Damon, Edgar Ramírez, Joan Allen, Julia S...","585,131",$227.47M
226,227.,Stalker,1979,162 min,"Drama, Sci-Fi",8.2,A guide leads two men through an area known as...,Andrei Tarkovsky,"Alisa Freyndlikh, Aleksandr Kaydanovskiy, Anat...","102,090",$0.23M
227,228.,Relatos salvajes,2014,122 min,"Comedy, Drama, Thriller",8.1,Six short stories that explore the extremities...,Damián Szifron,"Darío Grandinetti, María Marull, Mónica Villa,...","156,822",$3.11M
228,229.,Hachi: A Dog's Tale,2009,93 min,"Drama, Family",8.1,A college professor bonds with an abandoned do...,Lasse Hallström,"Richard Gere, Joan Allen, Cary-Hiroyuki Tagawa...","230,515",NaN
229,230.,How to Train Your Dragon,2010,98 min,"Animation, Action, Adventure",8.1,A hapless young Viking who aspires to hunt dra...,"Dean DeBlois, Chris Sanders","Jay Baruchel, Gerard Butler, Christopher Mintz...","625,418",$217.58M
230,231.,Annie Hall,1977,93 min,"Comedy, Romance",8,Neurotic New York comedian Alvy Singer falls i...,Woody Allen,"Woody Allen, Diane Keaton, Tony Roberts, Carol...","240,067",$39.20M
231,232.,Ben-Hur,1959,212 min,"Adventure, Drama, History",8.1,When a Jewish prince is betrayed and sent into...,William Wyler,"Charlton Heston, Jack Hawkins, Stephen Boyd, H...","205,573",$74.70M
232,233.,Before Sunrise,1995,101 min,"Drama, Romance",8.1,A young man and woman meet on a train in Europ...,Richard Linklater,"Ethan Hawke, Julie Delpy, Andrea Eckert, Hanno...","245,235",$5.54M
233,234.,Faa yeung nin wa,2000,98 min,"Drama, Romance",8.1,"Two neighbors, a woman and a man, form a stron...",Kar-Wai Wong,"Tony Chiu-Wai Leung, Maggie Cheung, Ping Lam S...","109,728",$2.73M
234,235.,Hotel Rwanda,2004,121 min,"Biography, Drama, History",8.1,Paul Rusesabagina was a hotel manager who hous...,Terry George,"Don Cheadle, Sophie Okonedo, Joaquin Phoenix, ...","318,593",$23.53M
235,236.,Butch Cassidy and the Sundance Kid,1969,110 min,"Biography, Crime, Drama",8,"Wyoming, early 1900s. Butch Cassidy and The Su...",George Roy Hill,"Paul Newman, Robert Redford, Katharine Ross, S...","191,250",$102.31M
236,237.,Gandhi,1982,191 min,"Biography, Drama, History",8,Gandhi's character is fully explained as a man...,Richard Attenborough,"Ben Kingsley, John Gielgud, Rohini Hattangadi,...","209,923",$52.77M
237,238.,Barry Lyndon,1975,185 min,"Adventure, Drama, History",8.1,An Irish rogue wins the heart of a rich widow ...,Stanley Kubrick,"Ryan O'Neal, Marisa Berenson, Patrick Magee, H...","136,364",NaN
238,239.,Salinui chueok,2003,131 min,"Action, Crime, Drama",8.1,"In a small Korean province in 1986, three dete...",Bong Joon Ho,"Kang-ho Song, Sang-kyung Kim, Roe-ha Kim, Jae-...","107,812",$0.01M
239,240.,Life of Brian,1979,94 min,Comedy,8.1,Born on the original Christmas in the stable n...,Terry Jones,"Graham Chapman, John Cleese, Michael Palin, Te...","342,558",$20.05M
240,241.,Mou gaan dou,2002,101 min,"Crime, Drama, Mystery",8.1,A story between a mole in the police departmen...,"Andrew Lau, Alan Mak","Andy Lau, Tony Chiu-Wai Leung, Anthony Chau-Sa...","113,062",$0.17M
241,242.,La haine,1995,98 min,"Crime, Drama",8.1,24 hours in the lives of three young men in th...,Mathieu Kassovitz,"Vincent Cassel, Hubert Koundé, Saïd Taghmaoui,...","135,221",$0.31M
242,243.,In the Name of the Father,1993,133 min,"Biography, Drama",8.1,A man's coerced confession to an IRA bombing h...,Jim Sheridan,"Daniel Day-Lewis, Pete Postlethwaite, Alison C...","144,928",$25.01M
243,244.,Amores perros,2000,154 min,"Drama, Thriller",8.1,A horrific car accident connects three stories...,Alejandro G. Iñárritu,"Emilio Echevarría, Gael García Bernal, Goya To...","210,588",$5.38M
244,245.,Network,1976,121 min,Drama,8.1,A television network cynically exploits a dera...,Sidney Lumet,"Faye Dunaway, William Holden, Peter Finch, Rob...","134,955",NaN
245,246.,Kaze no tani no Naushika,1984,117 min,"Animation, Adventure, Fantasy",8.1,Warrior and pacifist Princess Nausicaä despera...,Hayao Miyazaki,"Sumi Shimamoto, Mahito Tsujimura, Hisako Kyôda...","131,865",$0.50M
246,247.,The Maltese Falcon,1941,100 min,"Film-Noir, Mystery",8,A private detective takes on a case that invol...,John Huston,"Humphrey Bogart, Mary Astor, Gladys George, Pe...","142,650",$2.11M
247,248.,Persona,1966,85 min,"Drama, Thriller",8.1,A nurse is put in charge of a mute actress and...,Ingmar Bergman,"Bibi Andersson, Liv Ullmann, Margaretha Krook,...","90,342",NaN
248,249.,The Grapes of Wrath,1940,129 min,"Drama, History",8,A poor Midwest family is forced off their land...,John Ford,"Henry Fonda, Jane Darwell, John Carradine, Cha...","82,315",$0.06M
249,250.,Jaws,1975,124 min,"Adventure, Drama, Thriller",8,When a killer shark unleashes chaos on a beach...,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...","519,434",$260.00M